require 'test/unit'
require File.dirname(__FILE__) + '/../lib/iso7816'

class TestAPDU < Test::Unit::TestCase

  def setup
  end
  
  def s2b str
    ISO7816.s2b str
  end

  def test_apdus
    ISO7816::APDU::ACTIVATE_FILE.new
    ISO7816::APDU::APPEND_RECORD.new
    ISO7816::APDU::CHANGE_REFERENCE_DATA.new
    ISO7816::APDU::CREATE_FILE.new
    ISO7816::APDU::DEACTIVATE_FILE.new
    ISO7816::APDU::DELETE_FILE.new
    ISO7816::APDU::DISABLE_VERIFICATION_REQUIREMENT.new
    ISO7816::APDU::ENABLE_VERIFICATION_REQUIREMENT.new
    ISO7816::APDU::ENVELOPE.new
    ISO7816::APDU::ERASE_BINARY.new
    ISO7816::APDU::ERASE_RECORD.new
    ISO7816::APDU::EXTERNAL_AUTHENTICATE.new
    ISO7816::APDU::GENERAL_AUTHENTICATE.new
    ISO7816::APDU::GENERATE_ASYMMETRIC_KEY_PAIR.new
    ISO7816::APDU::GET_CHALLENGE.new
    ISO7816::APDU::GET_DATA.new
    ISO7816::APDU::GET_RESPONSE.new
    ISO7816::APDU::INTERNAL_AUTHENTICATE.new
    ISO7816::APDU::MANAGE_CHANNEL.new
    ISO7816::APDU::MANAGE_SECURITY_ENVIRONMENT.new
    ISO7816::APDU::PERFORM_SCQL_OPERATION.new
    ISO7816::APDU::PERFORM_SECURITY_OPERATION.new
    ISO7816::APDU::PERFORM_TRANSACTION_OPERATION.new
    ISO7816::APDU::PERFORM_USER_OPERATION.new
    ISO7816::APDU::PUT_DATA.new
    ISO7816::APDU::READ_BINARY.new
    ISO7816::APDU::READ_RECORD.new
    ISO7816::APDU::RESET_RETRY_COUNTER.new
    ISO7816::APDU::SEARCH_BINARY.new
    ISO7816::APDU::SEARCH_RECORD.new
    ISO7816::APDU::SELECT.new
    ISO7816::APDU::TERMINATE_CARD_USAGE.new
    ISO7816::APDU::TERMINATE_DF.new
    ISO7816::APDU::TERMINATE_EF.new
    ISO7816::APDU::UPDATE_BINARY.new
    ISO7816::APDU::UPDATE_RECORD.new
    ISO7816::APDU::VERIFY.new
    ISO7816::APDU::WRITE_BINARY.new
    ISO7816::APDU::WRITE_RECORD.new
    assert true
  end
end
